/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package work1;

import java.awt.TextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class playerchoice extends javax.swing.JFrame {

    /**
     * Creates new form playerchoice
     */
    public playerchoice() {
        initComponents();
        this.setTitle("BHAWNA");
       showroot();
      
    }
    void showroot()
    {
        jComboBox1.removeAllItems();
        String rootid=String.valueOf(jComboBox1.getSelectedItem());
        try
        {
            Connection con=project_logics.GetDataFromDataBase.getDbInstance();
            PreparedStatement pstmt=con.prepareStatement("select * from root");           
            ResultSet rs=pstmt.executeQuery();
            while(rs.next())
            {
             jComboBox1.addItem(rs.getString("rootname"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error is --> "+e);
        }   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form EBBHBBHBditor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jComboBox2 = new javax.swing.JComboBox();
      jLabel3 = new javax.swing.JLabel();
      jComboBox1 = new javax.swing.JComboBox();
      jLabel1 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      kGradientPanel1 = new keeptoo.KGradientPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(1200, 900));
      setUndecorated(true);
      getContentPane().setLayout(null);

      jPanel1.setBackground(new java.awt.Color(51, 255, 102));
      jPanel1.setLayout(null);

      jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jPanel1.add(jLabel5);
      jLabel5.setBounds(220, 140, 180, 40);

      jPanel2.setBackground(new java.awt.Color(248, 176, 34));
      jPanel2.setLayout(null);

      jButton1.setBackground(new java.awt.Color(255, 204, 204));
      jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
      jButton1.setText("NEXT");
      jButton1.setMinimumSize(new java.awt.Dimension(1200, 900));
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      jPanel2.add(jButton1);
      jButton1.setBounds(180, 260, 190, 60);

      jComboBox2.setBackground(new java.awt.Color(255, 204, 204));
      jComboBox2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EASY", "MEDIUM", "HARD" }));
      jComboBox2.setName(""); // NOI18N
      jPanel2.add(jComboBox2);
      jComboBox2.setBounds(300, 170, 180, 50);

      jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
      jLabel3.setText("LEVEL");
      jPanel2.add(jLabel3);
      jLabel3.setBounds(120, 180, 170, 40);

      jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
      jComboBox1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
      jComboBox1.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBox1ItemStateChanged(evt);
         }
      });
      jComboBox1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
         }
      });
      jPanel2.add(jComboBox1);
      jComboBox1.setBounds(300, 100, 180, 50);

      jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
      jLabel1.setText("ENTER YOUR NAME");
      jPanel2.add(jLabel1);
      jLabel1.setBounds(100, 40, 180, 53);

      jTextField1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
      jTextField1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1ActionPerformed(evt);
         }
      });
      jPanel2.add(jTextField1);
      jTextField1.setBounds(300, 40, 180, 50);

      jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
      jLabel2.setText("ROOT");
      jPanel2.add(jLabel2);
      jLabel2.setBounds(110, 100, 150, 40);
      jPanel2.add(kGradientPanel1);
      kGradientPanel1.setBounds(10, 10, 1500, 1000);

      jPanel1.add(jPanel2);
      jPanel2.setBounds(-10, -10, 1620, 1060);

      getContentPane().add(jPanel1);
      jPanel1.setBounds(0, 0, 1500, 1000);

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
      
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String name=jTextField1.getText();
     String date=String.valueOf(project_logics.GetDataFromDataBase.getpresentdate());
     String root=String.valueOf(jComboBox1.getSelectedItem());
     String level=String.valueOf(jComboBox2.getSelectedItem());
     if(jTextField1.getText().equals(""))
     {
      JOptionPane.showMessageDialog(null,"Enter your name");
     }
     else
     {
        dispose();
        new gameframe(name,root,level,date).setVisible(true);
        
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playerchoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playerchoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playerchoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playerchoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playerchoice().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JComboBox jComboBox1;
   private javax.swing.JComboBox jComboBox2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField jTextField1;
   private keeptoo.KGradientPanel kGradientPanel1;
   // End of variables declaration//GEN-END:variables
}
