/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package work1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class questiondeletion extends javax.swing.JFrame {
int total_ques_count=0;

   public String root_id; 
    ArrayList<Integer> abc=new ArrayList<>();
   /**
    * Creates new form questiondeletion
    */
   public questiondeletion(String root,String level,int lmt,int total_ques) {
        initComponents();
      this.setTitle("BHAWNA");
        jTextField1.setText(root);
        jTextField2.setText(lmt+"");
       jTextField3.setText(level);
       jTextField4.setText(total_ques+"");
        totalCount(root,level);
        jTextField4.setText(abc.size()+"");
      
   }

//   questiondeletion(String choice, String level, String root, String abc) {
//      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//   }

//   private questiondeletion() {
//      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//   }
void totalCount(String root,String level)
    {
    try
    {
     Connection con=project_logics.GetDataFromDataBase.getDbInstance();
     PreparedStatement pstmt=con.prepareStatement("select * from question_record where `roottype`=? and `level`=?");
     pstmt.setString(1,root);
     pstmt.setString(2,level);
     ResultSet rs=pstmt.executeQuery();
     while(rs.next())
     {
        abc.add(rs.getInt("ques_id")) ;
     }
    }
    catch(Exception e)
    {
      JOptionPane.showMessageDialog(null,"Exception is -->"+e);
    }
}
    
  
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setForeground(new java.awt.Color(51, 255, 153));
        jPanel1.setLayout(null);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(370, 490, 21, 32);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(370, 420, 21, 31);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ques_id", "roottype", "level", "questions", "opt1", "opt2", "opt3", "opt4", "answer"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 699, 91);

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel6.setText("ROOT TABLE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 160, 130, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton2.setText("SHOW DATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 420, 160, 50);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton1.setText("DELETE DATA");
        jButton1.setMinimumSize(new java.awt.Dimension(800, 800));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 490, 190, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 290, 393, 110);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel5.setText("QUESTIONS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 310, 110, 50);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(410, 420, 112, 40);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(410, 490, 112, 40);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(240, 420, 110, 40);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(240, 490, 110, 43);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(200, 430, 21, 21);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(200, 500, 21, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(280, 60, 120, 37);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel1.setText("ROOT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 60, 83, 29);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(280, 110, 121, 40);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setText("UPDATE LIMIT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 110, 130, 40);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setText("LEVEL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 50, 79, 38);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(610, 50, 101, 38);

        jTextField4.setEditable(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(610, 110, 104, 41);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setText("EXTRA QUESTIONS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 110, 170, 40);

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setLayout(null);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(830, 10, 70, 60);
        jPanel2.add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1500, 1000);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 20, 910, 1000);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 1500, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jRadioButton2ActionPerformed

   private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField6ActionPerformed

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField2ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String root1=String.valueOf(jTextField1.getText());
    String level=String.valueOf(jTextField3.getText());
    String limit=String.valueOf(jTextField2.getText());
    String rid=String.valueOf(project_logics.GetDataFromDataBase.getRootid(root1));
    DefaultTableModel dtm1=(DefaultTableModel)jTable1.getModel();
    int row_number=jTable1.getSelectedRow();
    String id=(dtm1.getValueAt(row_number,0).toString());
    try
    {
     Class.forName("com.mysql.jdbc.Driver");
     Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
     PreparedStatement pstmt=con.prepareStatement("delete from question_record where `ques_id`=?");
     pstmt.setString(1,id);
     
     int z=pstmt.executeUpdate();
    if(z>0)
    {
       JOptionPane.showMessageDialog(null,"value deleted");
       int entered_ques=project_logics.GetDataFromDataBase.getTotalCount(rid,level);
       int kyc=project_logics.GetDataFromDataBase.updateEnteredQuestionCountAfterDeletion(entered_ques,rid,level);
       int entered_ques1=project_logics.GetDataFromDataBase.getTotalCount(rid,level);
       jTextArea1.setText(entered_ques1+"");
   try
   {
     Class.forName("com.mysql.jdbc.Driver");
      Connection con1=project_logics.GetDataFromDataBase.getDbInstance();
     PreparedStatement pstmt1=con1.prepareStatement("select * from question_record where 'roottype`=? and `level`=?");
     pstmt1.setString(1,root1);
     pstmt1.setString(2,level);
     ResultSet rs=pstmt1.executeQuery();
     jTable1.setModel(DbUtils.resultSetToTableModel(rs));  
  pstmt1.close();
  con1.close();   
   }
    
   catch(Exception e)
   {
    JOptionPane.showMessageDialog(null,"error is---"+e);
   }
  }
   else
   {
    JOptionPane.showMessageDialog(null,"value not deleted");
   }
pstmt.close();
con.close();
   }
   catch(Exception el)
   {
    JOptionPane.showMessageDialog(null,"exception is"+el);          
   }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
     int row_number=jTable1.getSelectedRow();
     int id=Integer.parseInt(dtm.getValueAt(row_number,0).toString());
     
     String ques=(dtm.getValueAt(row_number,4).toString());
     String opt1=(dtm.getValueAt(row_number,5).toString());
     String opt2=(dtm.getValueAt(row_number,6).toString());
     String opt3=(dtm.getValueAt(row_number,7).toString());
     String opt4=(dtm.getValueAt(row_number,8).toString());
     
     jTextArea1.setText(ques);
     jTextField5.setText(opt1);
     jTextField7.setText(opt2);
     jTextField6.setText(opt3);
     jTextField8.setText(opt4);
   }//GEN-LAST:event_jTable1MouseClicked

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try
     {
       Connection con=project_logics.GetDataFromDataBase.getDbInstance();
       PreparedStatement pstmt=con.prepareStatement("select * from question_record");
       ResultSet rs=pstmt.executeQuery();
       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      }
      catch(Exception e)
      {
       JOptionPane.showMessageDialog(null,"error is-->"+e);
      }
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      dispose();
   }//GEN-LAST:event_jButton3ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(questiondeletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(questiondeletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(questiondeletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(questiondeletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new questiondeletion("","",0,0).setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
