package work1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import project_logics.GetDataFromDataBase;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADMIN
 */
public class Updatelimit extends javax.swing.JFrame {

   /**
    * Creates new form frame3
    */
   public Updatelimit() {
      initComponents();
      this.setTitle("BHAWNA");
      showroot();
   }

   void showroot() {
      jComboBox1.removeAllItems();
      String rootid = String.valueOf(jComboBox1.getSelectedItem());
      try {

    //Class.forName("com.mysql.jdbc.Driver");
         //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
         Connection con = project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt = con.prepareStatement("select * from root;");
         ResultSet rs = pstmt.executeQuery();

         while (rs.next()) {
            jComboBox1.addItem(rs.getString("rootname"));
         }
      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error is --> " + e);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel2.setLayout(null);

        kGradientPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2);
        jButton2.setBounds(870, 30, 90, 70);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel1.setText("SELECT ROOT");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(310, 90, 140, 40);

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jComboBox1);
        jComboBox1.setBounds(470, 90, 150, 50);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setText("SELECT DIFFICULTY");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(270, 160, 190, 40);

        jComboBox2.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        kGradientPanel1.add(jComboBox2);
        jComboBox2.setBounds(470, 160, 150, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setText("ENTER LIMIT OF DATA");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(260, 220, 200, 50);

        jTextField1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1);
        jTextField1.setBounds(470, 230, 150, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1);
        jButton1.setBounds(350, 310, 130, 50);

        jPanel2.add(kGradientPanel1);
        kGradientPanel1.setBounds(-10, 0, 1500, 1000);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1500, 670);

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("quiz");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("quiz1");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("questions");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("updatequestions");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
      dispose();
      new questions().setVisible(true);
   }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

   private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
      dispose();
      new quiz().setVisible(true);
   }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

   private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
      dispose();
      new quiz1().setVisible(true);
   }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

   private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
      dispose();
      new Updatelimit().setVisible(true);
   }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     dispose();
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jComboBox1ActionPerformed

   private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
      String my_selected_root = String.valueOf(jComboBox1.getSelectedItem());//root
      // String level=String.valueOf(jComboBox2.getSelectedItem());//difficulty
      String rootid = String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));//rootid

      //String limit=jTextField1.getText();
      try {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con = project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt = con.prepareStatement("select `level` from subroot where `rootid`=?");
         pstmt.setString(1, rootid);
         ResultSet rs = pstmt.executeQuery();
         jComboBox2.removeAllItems();
         while (rs.next()) {
            jComboBox2.addItem(rs.getString("level"));
         }

      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error is --> " + e);
      }

   }//GEN-LAST:event_jComboBox1ItemStateChanged

   private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
      String my_selected_root = String.valueOf(jComboBox1.getSelectedItem());//root
      String level = String.valueOf(jComboBox2.getSelectedItem());//difficulty
      //String root_id=String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));//rootid
      String rootid = String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));//rootid
      jTextField1.setText("");
      //String limit=jTextField1.getText();
      try {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con = project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt = con.prepareStatement("select `limit` from subroot where `rootid`=? and `level`=? ");
         pstmt.setString(1, rootid);
         pstmt.setString(2, level);
         ResultSet rs = pstmt.executeQuery();
         //jComboBox2.removeAllItems();
         while (rs.next()) {
            jTextField1.setText(rs.getString("limit"));
         }

      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error is --> " + e);
      }

   }//GEN-LAST:event_jComboBox2ItemStateChanged

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField1ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String my_selected_root = String.valueOf(jComboBox1.getSelectedItem());//root
      String level = String.valueOf(jComboBox2.getSelectedItem());//difficulty
      //String root_id=String.valueOf(jComboBox1.getSelectedItem()+1);//rootid
      String root_id = String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));//rootid
      String limit = jTextField1.getText();

      try {
         Connection con = project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt = con.prepareStatement("Update subroot set `limit`=? where `rootid`=? and `level`=?");

         pstmt.setString(1,limit);
         pstmt.setString(2,root_id);
         pstmt.setString(3,level);

         int aa = pstmt.executeUpdate();
         if (aa > 0) {
            JOptionPane.showMessageDialog(null, "value updated");
            int a = Integer.parseInt(jTextField1.getText());
            int flag = project_logics.GetDataFromDataBase.getTotalCount(root_id, level);
            if (a > flag) {
               dispose();
               new questiondeletion(my_selected_root, level, a, flag).setVisible(true);

            }
            else {
               System.out.println("errooorrrrrrr");
            }
            if(a<=flag)
            {
               dispose();
               new questiondeletion(my_selected_root, level, a, flag).setVisible(true);
               JOptionPane.showMessageDialog(null,"real value updated");
            }
            else
            {
               System.out.println("error is--");
            }
         }
         else
         {
            JOptionPane.showMessageDialog(null, "details not saved");
         }

      }
      catch (Exception e1)
      {
         System.out.println("Exception is --> " + e1);
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Updatelimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Updatelimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Updatelimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Updatelimit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Updatelimit().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
