/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package work1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class updatequestions extends javax.swing.JFrame {

    /**
     * Creates new form updatequestions
     */
    public updatequestions() {
        initComponents();
        this.setTitle("BHAWNA");
        showroot();
    }
    void showroot(){
    jComboBox1.removeAllItems();
    String rootid=String.valueOf(jComboBox1.getSelectedItem());
    try{
            
    //Class.forName("com.mysql.jdbc.Driver");
    //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
    Connection con=project_logics.GetDataFromDataBase.getDbInstance();            
    PreparedStatement pstmt=con.prepareStatement("select * from root;");
    ResultSet rs=pstmt.executeQuery();

    while(rs.next())
    {
     jComboBox1.addItem(rs.getString("rootname"));
    }
    }
    catch(Exception e)
    {
      JOptionPane.showMessageDialog(null,"Error is --> "+e);
    }     
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ques_id", "roottype", "level", "questions", "opt1", "opt2", "opt3", "opt4", "answer"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 180, 768, 90);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel4.setText("ROOT TABLE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 130, 130, 50);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 400, 150, 49);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 460, 150, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(260, 290, 280, 90);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setText("Selected Questions");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 310, 177, 45);

        jTextField3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(360, 420, 100, 40);

        jTextField4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(360, 470, 100, 40);

        buttonGroup1.add(jRadioButton4);
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(320, 480, 21, 31);

        buttonGroup1.add(jRadioButton3);
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(320, 420, 21, 31);

        jTextField1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 420, 107, 40);

        jTextField2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 470, 107, 40);

        buttonGroup1.add(jRadioButton2);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(150, 480, 21, 30);

        jPanel3.setBackground(new java.awt.Color(255, 153, 204));
        jPanel3.setLayout(null);

        jComboBox2.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(430, 30, 140, 50);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(610, 30, 140, 50);

        buttonGroup1.add(jRadioButton1);
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(120, 390, 21, 30);

        jComboBox1.setBackground(new java.awt.Color(255, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(170, 30, 150, 50);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel1.setText("Roottype");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(70, 40, 90, 30);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setText("LEVEL");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(350, 40, 74, 29);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 30, 850, 510);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(890, 0, 70, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1500, 700);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("File");

        jMenuItem1.setText("quiz");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("quiz1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("questions");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("updatelimit");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      dispose();
      new quiz().setVisible(true);
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     dispose();
     new quiz1().setVisible(true);
     
   }//GEN-LAST:event_jMenuItem2ActionPerformed

   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     dispose();
     new questions().setVisible(true);
   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
      dispose();
      new Updatelimit().setVisible(true);
   }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      dispose();
   }//GEN-LAST:event_jButton5ActionPerformed

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jComboBox1ActionPerformed

   private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
      String my_selected_root=String.valueOf(jComboBox1.getSelectedItem());
      String rootid=String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));
      try
      {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt=con.prepareStatement("select `level` from subroot where `rootid`=?");
         pstmt.setString(1,rootid);
         ResultSet rs=pstmt.executeQuery();
         jComboBox2.removeAllItems();
         while(rs.next())
         {
            jComboBox2.addItem(rs.getString("level"));
         }

      }
      catch (Exception e)
      {
         JOptionPane.showMessageDialog(null,"Error is --> "+e);
      }
   }//GEN-LAST:event_jComboBox1ItemStateChanged

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try
      {
         Connection con=project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt=con.prepareStatement("Select * from question_record");
         ResultSet rs=pstmt.executeQuery();

         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         pstmt.close();
         con.close();
      }
      catch (Exception e)
      {
         JOptionPane.showMessageDialog(null,"Error is --> "+e);
      }
   }//GEN-LAST:event_jButton3ActionPerformed

   private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
      String my_selected_root=String.valueOf(jComboBox1.getSelectedItem());//root
      String level=String.valueOf(jComboBox2.getSelectedItem());//difficulty
      String rootid=String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));
      jTextField1.setText("");
      try
      {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt=con.prepareStatement("select `limit` from subroot where `rootid`=? and `level`=? ");
         pstmt.setString(1,rootid);
         pstmt.setString(2,level);
         ResultSet rs=pstmt.executeQuery();
         while(rs.next())
         {
            //jTextField1.setText(rs.getString("limit"));
         }

      }
      catch (Exception e)
      {
         JOptionPane.showMessageDialog(null,"Error is --> "+e);
      }
   }//GEN-LAST:event_jComboBox2ItemStateChanged

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField1ActionPerformed

   private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked

   }//GEN-LAST:event_jTextArea1MouseClicked

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String my_selected_root=String.valueOf(jComboBox1.getSelectedItem());
      String level=String.valueOf(jComboBox2.getSelectedItem());
      String my_root_id=String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));
      try
      {
         Connection con=project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt=con.prepareStatement("delete from subroot where `rootid`=?");

         pstmt.setString(1,my_root_id);
         int rs=pstmt.executeUpdate();
         if(rs>0)
         {
            JOptionPane.showMessageDialog(null,"value deleted");
            int abc=project_logics.GetDataFromDataBase.deleteSubRoot(my_selected_root,level);
         }
         else
         {
            JOptionPane.showMessageDialog(null,"value not  deleted");
         }
      }
      catch(Exception e)
      {
         System.out.println("error is "+e);
      }
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String my_selected_root=String.valueOf(jComboBox1.getSelectedItem());
      String questions=jTextArea1.getText();
      String opt1=jTextField1.getText();
      String opt2=jTextField2.getText();
      String opt3=jTextField3.getText();
      String opt4=jTextField4.getText();
      String level=String.valueOf(jComboBox2.getSelectedItem());
      //String roottype=String.valueOf(project_logics.GetDataFromDataBase.getRootid(my_selected_root));
      DefaultTableModel dtm1 =(DefaultTableModel)jTable1.getModel();
      int row_number=jTable1.getSelectedRow();
      String id=(dtm1.getValueAt(row_number,0).toString());
      String answer=null;
      if(jRadioButton1.isSelected())
      {
         answer=jTextField1.getText();
      }
      else if(jRadioButton2.isSelected())
      {
         answer=jTextField2.getText();
      }
      else if(jRadioButton3.isSelected())
      {
         answer=jTextField3.getText();
      }
      else if(jRadioButton4.isSelected())
      {
         answer=jTextField4.getText();
      }
      try
      {
         Connection con=project_logics.GetDataFromDataBase.getDbInstance();
         PreparedStatement pstmt=con.prepareStatement("Update question_record set `questions`=?,`opt1`=?,`opt2`=?,`opt3`=?,`opt4`=?,`answer`=? where `ques_id`=?");
         pstmt.setString(1,questions);
         pstmt.setString(2,opt1);
         pstmt.setString(3,opt2);
         pstmt.setString(4,opt3);
         pstmt.setString(5,opt4);
         pstmt.setString(6,answer);
         pstmt.setString(7,id);
         int aa=pstmt.executeUpdate();
         if(aa>0)
         {
            JOptionPane.showMessageDialog(null,"value updated");
         }
         else
         {
            JOptionPane.showMessageDialog(null,"value not updated!!!");
         }
      }
      catch(Exception e)
      {
         JOptionPane.showMessageDialog(null,"Exception is --> "+e);
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
      int row_number=jTable1.getSelectedRow();
      int id=Integer.parseInt(dtm.getValueAt(row_number,0).toString());

      String questions=(dtm.getValueAt(row_number,4).toString());
      String opt1=(dtm.getValueAt(row_number,5).toString());
      String opt2=(dtm.getValueAt(row_number,6).toString());
      String opt3=(dtm.getValueAt(row_number,7).toString());
      String opt4=(dtm.getValueAt(row_number,8).toString());

      jTextArea1.setText(questions);
      jTextField1.setText(opt1);
      jTextField2.setText(opt2);
      jTextField3.setText(opt3);
      jTextField4.setText(opt4);
   }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatequestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatequestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatequestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatequestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatequestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
